# Connection config
CONNECT_TO_MOV_API = False
CONNECT_TO_TOP_CAM = False
CONNECT_TO_FRONT_CAM = False

# Debug config
TEST_SEG_WITH_VID = False
DEBUG_NAV = True
DEBUG_CAM = False
DEBUG_ARM = True

# Default values config
DEFAULT_VERTICAL_PRECISION = 4
DEFAULT_HORIZONTAL_PRECISION = 10