# Connection config
CONNECT_TO_MOV_API = False
CONNECT_TO_TOP_CAM = False
CONNECT_TO_FRONT_CAM = False
CAN_MOVE = CONNECT_TO_MOV_API and False 

# Debug config
TEST_SEG_WITH_VID = False
DEBUG_NAV = False
DEBUG_CAM = False
DEBUG_ARM = False
DEBUG_SS8 = True

# Default scanning config
DEFAULT_VERTICAL_PRECISION = 4
DEFAULT_HORIZONTAL_PRECISION = 4
ARM_MOV_WAITING_TIME = 2
CENTER_THRESHOLD = 6
ALIGNMENT_SPEED = 2.3
ALIGNMENT_WAIT = 2