# Connection config
CONNECT_TO_MOV_API = True
CONNECT_TO_TOP_CAM = True
CONNECT_TO_FRONT_CAM = True
CAN_MOVE = CONNECT_TO_MOV_API and True 

# Debug config
TEST_SEG_WITH_VID = False
DEBUG_NAV = True
DEBUG_CAM = False
DEBUG_ARM = False           
DEBUG_SS8 = True
SKIP_CALLIBRATION_STEP = False

# Default scanning config
DEFAULT_VERTICAL_PRECISION = 4
DEFAULT_HORIZONTAL_PRECISION = 6
ARM_MOV_WAITING_TIME = 2
CENTER_THRESHOLD = 4
ALIGNMENT_SPEED = 1.5
ALIGNMENT_WAIT = 2
GALERE_TOLERANCE = 2

# LEDs config
LED_BRIGHTNESS = 4
